spring:
  application:
    name : configServer
  cloud:
    config:
      server:
        git:
          uri: file://D:\git-repo  #dar in masir bayad git init shavad
          default-label: master    #in property ham hatman bayad meghdar dashte bashad
server:
  port: 8889

#########################config client
#spring:
#  config:
#    import: optional:configserver:http://localhost:8889
#  application:
#    name: demo  this name =fisrt part name of config yml
#  profiles:
#    active: t2 this name =secound part name of config yml for example demo-t2.yml